version: "3"
networks:
  expense:
volumes:
  mysql:  # docker volume create mysql
services:
  mysql:
    image: joindevops/mysql:v1
    container_name: mysql # --name mysql
    volumes:
    - mysql:/var/lib/mysql # -v mysql:/var/lib/mysql