- name: mysql configuration
  hosts: mysql
  become: yes
  vars: 
    host: "mysql.learncloudwithamk.shop"
    mysql_user: "root"
    mysql_pwd: "ExpenseApp@1"
  tasks: 
  - name: Installing mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: starting and enabling mysqld service
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes