apiVersion: V1 
kind: Pod

metadata:
  name: single-prod
  labels: 
      prj: expense
      env: dev

spec:
  containers:
    - name: nginx
      iamge: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep", "1000"]