- name: Play 1
  hosts: web
  become: yes
  tasks:
   - name: Installing a package
     ansible.builtin.package:
      name: nginx
      state: present
   - name: running the nginx
     ansible.builtin.service:
      name: nginx
      enabled: yes
      state: restarted