- name: play1
  hosts: web
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: running nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes