- name: play1
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120 hrs"
  tasks: 
    - name: using variables
      ansible.builtin.debug:
        msg: I am learning "{{COURSE}}" with "{{DURATION}}"