- name: play1
  hosts: web
  vars:
    COURSE: "DevOps"
  tasks:
    - name: task level variables
      vars:
        COURSE: AWS
      ansbile.builtin.debug:
        msg: "I am learning {{COURSE}}"
      