- name: using vars_prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Enter COURSE
    private: false
  - name : DURATION
    prompt: Enter DURATION
    private: false
  tasks:
  - name: using vars_prompt
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}} of {{DURATION}}"