- name: Datatypes'
  hosts: local
  connection: local
  vars:
    course: DevOps
    duration: 120
    topics:
      - Linux
      - shell
      - ansible  
      - Terraform
      - K8s
      - Docker
    tools:
       ci: Jenkins
       CD: Spinnaker
       Cloud: AWS 
  tasks:
  - name: Printing the Datatypes
    ansible.builtin.debug:
      msg: "I am learning {{course}} of duration {{duration}}. Topics covered are {{topics}} and tools used are {{tools}}"