- name: filters/functions
  hosts: local
  connection: local
  vars_files:
   - vars_files.yaml
  tasks:
  - name: uppercase
    ansible.builtin.debug:
      msg: "{{ COURSE | upper }}"
  - name: lower
    ansible.builtin.debug:
      msg: "{{ DURATION | lower }}"
  - name: map to list
    vars:
      details:
        COURSE: "Devops with AWS"
        DURATION: " 120 hrs"
        TRAINER: "SKR"
    ansible.builtin.debug:
      msg: "{{ details | dict2items }}"