- name: filters
  hosts: local
  connection: local
  tasks:
    - name: upper case
      vars:
        greeting: "Hello World"
      ansible.builtin.debug:
        msg: "{{ greeting | upper }}"
    - name: lower case
      vars: 
        greeting: "HELLO WORLD" 
      ansible.builtin.debug:
        msg: "{{ greeting | lower }}"
    - name: map to list
      vars: 
        course:
          name: Devops
          time: 120
          place: zoom
      ansible.builtin.debug:
        msg: "{{ course | dict2items }}"
    - name: list to map
      vars:
       course:
        - {"key": "name","value": "Devops"}
        - {"key": "time","value": 120}
        - {"key": "place","value": "zoom"}
      ansible.builtin.debug:
        msg: "{{ course | items2dict }}"