- name: expense servers
  hosts: local
  connection: local
  vars:
    ami: ami-09c813fb71547fc4f
    sg_id: sg-01e389050814235b8
    subnet_id: subnet-0c0eb462a5bd2e4bc
    instances:
      - mysql
      - frontend
      - backend
    zone: learnwithamk.shop
  tasks:
  - name: Creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami }}"
    loop: "{{ instances }}"
    register: instances_info

  - name: adding route53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.instances_info[0] }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances_info[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ instances_info }}"